name: Converting my game to exe file

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]

    runs-on: ${{ matrix.os }}
       
    steps:
    - uses: actions/checkout@v4
      with:
        repository: ma3rd-nepon/pygame
        
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
          python-version: '3.10'
          cache: 'pip'

    - name: Install Dependencies
      with:
        run: pip install -r src/requirements.txt
      continue-on-error: true

    - name: Build code
      uses: Nuitka/Nuitka-Action@main
      with:
          nuitka-version: main
          script-name: game.py
          onefile: true
          standalone: true
          disable-console: true
          enable-plugins: pygame
          macos-create-app-bundle: true
          macos-target-arch: universal
          macos-app-mode: gui
          disable-cache: true
      
      continue-on-error: true

    - name: Give permissions
      with:
        run: chmod +x game.bin

    - name: Upload Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: ${{ matrix.os }} Build
        path: |
          build/*.exe
          build/*.bin
          build/*.app/**/*
      continue-on-error: true
