name: Converting program to exe file

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4
      with:
        repository: ma3rd-nepon/pygame

    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install nuitka
        pip install -r requirements.txt
      continue-on-error: true

    - name: Build Exe
      uses: Nuitka/Nuitka-Action@main
      with:
          nuitka-version: main
          script-name: game.py
          onefile: true
          standalone: true
          disable-cache: true
      continue-on-error: true

    - name: Upload Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: Windows Build
        path: |
          build/*.exe
          build/*.bin
          build/*.cmd/**/*
      continue-on-error: true
      if: ${{ always() }}
